### ISSUE TITLE
ksbuilder create 的问题

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/ksbuilder#60]
```
root@stonetest1:/tmp# ksbuilder create
Please input extension name: pvc-auto-resizer
✔ storage
Please input extension author: stoneshi
Please input Email (optional): stoneshi@yunify.com
Please input author's URL (optional):
Directory: /tmp/pvc-auto-resizer

The extension charts has been created.
root@stonetest1:/tmp#
root@stonetest1:/tmp# cd /tmp/pvc-auto-resizer
root@stonetest1:/tmp/pvc-auto-resizer# ls
README.md  README_zh.md  applicationclass.yaml	charts	extension.yaml	permissions.yaml  static  values.yaml
root@stonetest1:/tmp/pvc-auto-resizer# cd charts
root@stonetest1:/tmp/pvc-auto-resizer/charts# ls
backend  frontend
root@stonetest1:/tmp/pvc-auto-resizer/charts# cd backend/
root@stonetest1:/tmp/pvc-auto-resizer/charts/backend# ls
Chart.yaml  templates  values.yaml
root@stonetest1:/tmp/pvc-auto-resizer/charts/backend# cat Chart.yaml
apiVersion: v1
name: backend
description: Backend of pvc-auto-resizer extension.
type: application
version: 0.0.1
appVersion: "0.0.1"
```

问题：
- 生成的Chart.yaml中的 apiVersion 是v1, 应为v2
- ksbuilder create时，能否指定frontend/backend 的chart名称。因为backend有点抽象，改个具体的名称比较好，手动改的话，需要同时改 Chart.yaml templates/helper.tpl 等地方，很繁琐
- ksbuilder create 应生成 changelog 文件
- 如若一个extension支持英文，请打包或校验(validate) 时，确保extension.yaml 中的displayname, description, provider 都提供了英文信息，缺一不可。

**Comment by iawia002** [comment]
> ksbuilder create时，能否指定frontend/backend 的chart名称

这个有待商榷吧，步骤太多（即便是可选的）也会让使用体验变得不好的，这个属于非常细节的东西了，脚手架创建出来的始终只是一个模板

**Comment by stoneshi-yunify** [comment]
> > 生成的Chart.yaml中的 apiVersion 是v1, 应为v2
> 
> 这个其实 #59 已经改了，后面我一起发个版本
> 
> > ksbuilder create时，能否指定frontend/backend 的chart名称
> 
> 这个有待商榷吧，步骤太多（即便是可选的）也会让使用体验变得不好的，这个属于非常细节的东西了，脚手架创建出来的始终只是一个模板

froentend/backend， 跟我用helm create frontend/backend，应该是一样的吧？这样的话，用户想修改的话，就直接在charts/ 下 helm create xxx 就好了。

**Comment by iawia002** [comment]
> froentend/backend， 跟我用helm create frontend/backend，应该是一样的吧？这样的话，用户想修改的话，就直接在charts/ 下 helm create xxx 就好了。

内容不一样，里面我们加了一些 extension 需要的 CR 资源

**Comment by stoneshi-yunify** [comment]
> > froentend/backend， 跟我用helm create frontend/backend，应该是一样的吧？这样的话，用户想修改的话，就直接在charts/ 下 helm create xxx 就好了。
> 
> 内容不一样，里面我们加了一些 extension 需要的 CR 资源

那这样的话，我建议还是支持。你可以看下devops 和其他一些正在开发的extension, 基本没有使用 frontend/backend 这种原生名字的。改起来又很繁琐，容易出错。ksbuilder create 的时候就询问一下需不需要定制名字呗，回答no 就还保持frontend/backend。

**Comment by stoneshi-yunify** [comment]
使用 frontend/backend 原生名称，不指定什么 fullnameoverride nameoverride 之类的东西，安装出来的extension （pod) 的名字就是frontend/backend，太模糊了，根本就不知道是个什么应用。

**Comment by iawia002** [comment]
> 使用 frontend/backend 原生名称，不指定什么 fullnameoverride nameoverride 之类的东西，安装出来的extension （pod) 的名字就是frontend/backend，太模糊了，根本就不知道是个什么应用。

这个不对吧，安装出来的 Pod 是 extension 名称 + frontend/backend，比如我的 tower 就是 tower-backend，这个不算模糊

**Comment by stoneshi-yunify** [comment]
ok。那就先这样吧，以后再看看有没有人跟我有同样的疑问。

**Comment by iawia002** [comment]
[v0.3.1](https://github.com/kubesphere/ksbuilder/releases/tag/v0.3.1) 解决了问题 1 3 4，问题 2 待定
