### ISSUE TITLE
ksbuilder lint error with missing Chart.yaml file

### ISSUE THREAD

**Issue by junotx** [kubesphere/ksbuilder#76]
because the Extension uses extension.yaml instead of Chart.yaml
![截图_1705984765694](https://github.com/kubesphere/ksbuilder/assets/49136171/15715dd4-79a4-4bae-8140-b97180a55c52)

**Comment by iawia002** [comment]
cc @littleBlackHouse

**Comment by stoneshi-yunify** [comment]
如果没有 Chart.yaml, lint 就尝试先package 再lint吧

**Comment by benjaminhuo** [comment]
这个 lint 没有测试过吗？我们的扩展都是 extension.yaml

**Comment by pixiake** [comment]
看起来咱的extension并没有完全遵循helm的规范，@littleBlackHouse可以调整下lint策略，把helm的校验先屏蔽掉

**Comment by benjaminhuo** [comment]
> 看起来咱的extension并没有完全遵循helm的规范，@littleBlackHouse可以调整下lint策略，把helm的校验先屏蔽掉

@wansir
